"""ahost-helper: the only code that runs as root.

Invoked as `sudo /usr/local/sbin/ahost-helper <verb> [args]`. It takes app *names*, never file contents: it loads
the manifest itself, validates it (model + policy), and renders every file from its own templates. Config always
comes from /etc/ahost/ahost.toml (never from the environment or the caller).
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import syslog
from pathlib import Path

from . import host, policy, render
from .config import Config, load
from .manifest_io import load_all, load_app
from .models import NAME_RE, App
from .ports import Registry

CONFIG_PATH = Path("/etc/ahost/ahost.toml")
UNIT_ACTIONS = {"start", "stop", "restart", "enable", "disable", "reload"}


class HelperError(Exception):
    pass


def log(msg: str) -> None:
    caller = os.environ.get("SUDO_USER", "?")
    syslog.openlog("ahost-helper")
    syslog.syslog(syslog.LOG_INFO, f"caller={caller} {msg}")


def sh(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    r = subprocess.run(list(args), capture_output=True, text=True, check=False)
    if check and r.returncode != 0:
        raise HelperError(f"{' '.join(args)} failed ({r.returncode}): {r.stderr.strip() or r.stdout.strip()}")
    return r


# ---------------------------------------------------------------- loading & validation
def _cfg() -> Config:
    st = CONFIG_PATH.stat()
    if st.st_uid != 0 or st.st_mode & 0o022:
        raise HelperError(f"{CONFIG_PATH} must be owned by root and not group/world-writable")
    return load(CONFIG_PATH)


def _app(cfg: Config, name: str) -> App:
    if not NAME_RE.match(name):
        raise HelperError(f"invalid app name {name!r}")
    path = Path(cfg.paths.apps_dir) / f"{name}.toml"
    if path.is_symlink() or not path.is_file():
        raise HelperError(f"{path} is not a regular file")
    app = load_app(path)
    rep = policy.check(app, cfg)
    if not rep.ok:
        raise HelperError("policy: " + "; ".join(rep.errors))
    apps, _ = load_all(Path(cfg.paths.apps_dir))
    apps[name] = app
    dup = [e for e in policy.check_unique_domains(list(apps.values()), host.legacy_server_names(cfg))
           if any(f"domain {d} " in e for d in app.domains)]
    if dup:
        raise HelperError("; ".join(dup))
    return app


def _registry(cfg: Config) -> Registry:
    Path(cfg.paths.state_dir).mkdir(parents=True, exist_ok=True, mode=0o750)
    return Registry(Path(cfg.paths.state_dir) / "ahost.db", cfg)


def _facts(cfg: Config, app: App) -> render.Facts:
    from .gpu import minor_map
    return render.Facts(certs_present=host.certs_present(cfg),
                        gpu_minors=minor_map() if any(p.gpus for p in app.processes.values()) else {},
                        manifest_path=str(Path(cfg.paths.apps_dir) / f"{app.name}.toml"))


# ---------------------------------------------------------------- file writing
def write_atomic(path: str, content: str, mode: int) -> bool:
    """Write if changed. Returns True when the file changed."""
    p = Path(path)
    if p.exists() and not p.is_symlink() and p.read_text() == content and (p.stat().st_mode & 0o777) == mode:
        return False
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_name(f".{p.name}.ahost-tmp")
    with open(tmp, "w") as f:
        f.write(content)
    os.chown(tmp, 0, 0)
    os.chmod(tmp, mode)
    os.replace(tmp, p)
    return True


def _allowed_path(cfg: Config, path: str) -> None:
    """Every write must land in one of AHost's own directories."""
    norm = os.path.normpath(path)
    prefixes = (f"{cfg.paths.etc_dir}/apps/", f"{cfg.paths.systemd_dir}/ahost@", f"{cfg.nginx.sites_dir}/")
    if norm != path or ".." in path.split("/") or not norm.startswith(prefixes):
        raise HelperError(f"refusing to write outside AHost directories: {path}")


# ---------------------------------------------------------------- verbs
def v_apply_unit(cfg: Config, name: str) -> dict:
    app = _app(cfg, name)
    reg = _registry(cfg)
    ports = reg.resolve(app, commit=True)
    facts = _facts(cfg, app)
    changed = []
    for pid in app.processes:
        for a in render.render_process(app, pid, ports.get(pid), cfg, facts):
            _allowed_path(cfg, a.path)
            if write_atomic(a.path, a.content, a.mode):
                changed.append(a.path)
    if app.multi:
        # the target groups the processes; each process is PartOf it
        tgt = f"{cfg.paths.systemd_dir}/ahost@{app.name}.target.d/override.conf"
        wants = "\n".join(f"Wants={app.unit(p)}" for p in app.processes)
        if write_atomic(tgt, f"# Generated by AHost.\n[Unit]\n{wants}\n", 0o644):
            changed.append(tgt)
    # remove files of processes that no longer exist
    live = {app.instance(p) for p in app.processes}
    for f in Path(cfg.paths.etc_dir, "apps").glob(f"{app.name}*"):
        inst = f.name.rsplit(".", 1)[0]
        if (inst == app.name or inst.startswith(app.name + ":")) and inst not in live:
            f.unlink()
            changed.append(str(f))
    if changed:
        sh("systemctl", "daemon-reload")
    log(f"apply-unit app={name} changed={len(changed)} ports={ports}")
    return {"changed": changed, "ports": ports}


def _nginx_test_or_restore(backups: dict[str, str | None], symlinks: dict[str, str | None]) -> None:
    r = sh("nginx", "-t", check=False)
    if r.returncode == 0:
        return
    for path, old in backups.items():
        if old is None:
            Path(path).unlink(missing_ok=True)
        else:
            Path(path).write_text(old)
    for link, target in symlinks.items():
        Path(link).unlink(missing_ok=True)
        if target is not None:
            os.symlink(target, link)
    raise HelperError(f"nginx -t failed, restored previous config:\n{r.stderr.strip()}")


def v_apply_site(cfg: Config, name: str, *, swap_legacy: bool = False) -> dict:
    app = _app(cfg, name)
    reg = _registry(cfg)
    ports = {a.process: a.port for a in reg.all() if a.app == name}
    missing = [p for p, proc in app.processes.items() if proc.port is not None and p not in ports]
    if missing:
        raise HelperError(f"ports not allocated for {missing}; run apply-unit first")
    site = render.render_site(app, ports, cfg, _facts(cfg, app))
    if site is None:
        return {"changed": []}
    _allowed_path(cfg, site.path)
    Path(cfg.nginx.log_dir).mkdir(parents=True, exist_ok=True)
    Path(cfg.certs.webroot).mkdir(parents=True, exist_ok=True)
    old = Path(site.path).read_text() if Path(site.path).exists() else None
    symlinks: dict[str, str | None] = {}
    legacy_names = host.legacy_server_names(cfg)
    still_legacy = sorted({legacy_names[d] for d in app.domains if d in legacy_names})
    if still_legacy and not swap_legacy:
        raise HelperError(f"legacy site(s) {still_legacy} still serve this app's domains; use swap-site")
    if swap_legacy:
        legacy = _legacy_site(cfg, app)
        link = Path(cfg.nginx.legacy_enabled) / legacy
        if link.is_symlink():
            symlinks[str(link)] = os.readlink(link)
            link.unlink()
        elif link.exists():
            raise HelperError(f"{link} is a regular file, not a symlink; move it to sites-available first")
    changed = write_atomic(site.path, site.content, site.mode)
    if changed or symlinks:
        _nginx_test_or_restore({site.path: old}, symlinks)
        sh("systemctl", "reload", "nginx")
    log(f"apply-site app={name} swap={swap_legacy} changed={changed}")
    return {"changed": [site.path] if changed else [], "legacy_disabled": list(symlinks)}


def _legacy_site(cfg: Config, app: App) -> str:
    allow = policy.read_list(Path(cfg.paths.etc_dir) / "legacy.allow")
    site = app.legacy.site if app.legacy else None
    if not site or f"site:{site}" not in allow:
        raise HelperError(f"legacy site {site!r} is not listed as 'site:{site}' in {cfg.paths.etc_dir}/legacy.allow")
    if "/" in site or site.startswith("."):
        raise HelperError("invalid legacy site name")
    return site


def _legacy_unit(cfg: Config, app: App) -> str:
    allow = policy.read_list(Path(cfg.paths.etc_dir) / "legacy.allow")
    unit = app.legacy.unit if app.legacy else None
    if not unit or f"unit:{unit}" not in allow:
        raise HelperError(f"legacy unit {unit!r} is not listed as 'unit:{unit}' in {cfg.paths.etc_dir}/legacy.allow")
    return unit


def v_unswap_site(cfg: Config, name: str) -> dict:
    """Rollback: remove the generated site and re-enable the legacy one, in one reload."""
    app = _app(cfg, name)
    legacy = _legacy_site(cfg, app)
    site_path = f"{cfg.nginx.sites_dir}/{name}.conf"
    old = Path(site_path).read_text() if Path(site_path).exists() else None
    link = Path(cfg.nginx.legacy_enabled) / legacy
    if not link.exists():
        os.symlink(f"../{Path(cfg.nginx.legacy_available).name}/{legacy}", link)
    Path(site_path).unlink(missing_ok=True)
    _nginx_test_or_restore({site_path: old}, {str(link): None})
    sh("systemctl", "reload", "nginx")
    log(f"unswap-site app={name}")
    return {"legacy_enabled": str(link)}


def v_unit(cfg: Config, action: str, name: str) -> dict:
    if action not in UNIT_ACTIONS:
        raise HelperError(f"unit action must be one of {sorted(UNIT_ACTIONS)}")
    app = _app(cfg, name)
    units = [app.unit(p) for p in app.processes]
    if app.multi:
        target = f"ahost@{app.name}.target"
        # start/stop/restart act on the target (processes are PartOf it); enable/disable on everything
        units = [target] if action in ("start", "stop", "restart") else [target, *units]
    sh("systemctl", action, *units)
    log(f"unit {action} app={name} units={units}")
    return {"units": units}


def v_legacy_unit(cfg: Config, action: str, name: str) -> dict:
    if action not in UNIT_ACTIONS:
        raise HelperError(f"unit action must be one of {sorted(UNIT_ACTIONS)}")
    unit = _legacy_unit(cfg, _app(cfg, name))
    sh("systemctl", action, unit)
    log(f"legacy-unit {action} app={name} unit={unit}")
    return {"unit": unit}


def v_cert(cfg: Config, name: str) -> dict:
    app = _app(cfg, name)
    missing = render.missing_certs(app, _facts(cfg, app))
    issued = []
    for cert, domains in app.cert_groups().items():
        if cert not in missing:
            continue
        args = ["certbot", "certonly", "--non-interactive", "--agree-tos", "--webroot", "-w", cfg.certs.webroot,
                "--cert-name", cert, "--deploy-hook", "systemctl reload nginx"]
        if cfg.certs.email:
            args += ["-m", cfg.certs.email]
        else:
            args += ["--register-unsafely-without-email"]
        for d in domains:
            args += ["-d", d]
        sh(*args)
        issued.append(cert)
    log(f"cert app={name} issued={issued}")
    return {"issued": issued}


def v_remove(cfg: Config, name: str) -> dict:
    if not NAME_RE.match(name):
        raise HelperError("invalid app name")
    removed = []
    units = [f.name.removesuffix(".service.d") for f in Path(cfg.paths.systemd_dir).glob(f"ahost@{name}*.service.d")
             if re.fullmatch(rf"ahost@{re.escape(name)}(:[a-z0-9-]+)?\.service\.d", f.name)]
    if units:
        sh("systemctl", "disable", "--now", *[f"{u}.service" for u in units], check=False)
    for u in units:
        d = Path(cfg.paths.systemd_dir) / f"{u}.service.d"
        shutil.rmtree(d)
        removed.append(str(d))
    for f in Path(cfg.paths.etc_dir, "apps").glob(f"{name}*"):
        inst = f.name.rsplit(".", 1)[0]
        if inst == name or inst.startswith(name + ":"):
            f.unlink()
            removed.append(str(f))
    site = Path(cfg.nginx.sites_dir) / f"{name}.conf"
    if site.exists():
        old = site.read_text()
        site.unlink()
        removed.append(str(site))
        _nginx_test_or_restore({str(site): old}, {})
        sh("systemctl", "reload", "nginx")
    sh("systemctl", "daemon-reload")
    _registry(cfg).release(name)
    log(f"remove app={name} removed={len(removed)}")
    return {"removed": removed}


def v_install(cfg: Config) -> dict:
    """Install the shared files (template units, nginx common/default). Idempotent."""
    changed = []
    Path(cfg.nginx.sites_dir).mkdir(parents=True, exist_ok=True)
    Path(cfg.paths.etc_dir, "apps").mkdir(parents=True, exist_ok=True, mode=0o755)
    Path(cfg.nginx.log_dir).mkdir(parents=True, exist_ok=True)
    Path(cfg.certs.webroot).mkdir(parents=True, exist_ok=True)
    backups = {}
    for a in render.render_static(cfg):
        if a.path.startswith(cfg.nginx.sites_dir):
            backups[a.path] = Path(a.path).read_text() if Path(a.path).exists() else None
        if write_atomic(a.path, a.content, a.mode):
            changed.append(a.path)
    if any(p.startswith(cfg.nginx.sites_dir) for p in changed):
        _nginx_test_or_restore({p: backups[p] for p in changed if p in backups}, {})
        sh("systemctl", "reload", "nginx")
    if any(p.startswith(cfg.paths.systemd_dir) for p in changed):
        sh("systemctl", "daemon-reload")
    log(f"install changed={changed}")
    return {"changed": changed}


VERBS = {
    "install": (0, lambda c, a: v_install(c)),
    "apply-unit": (1, lambda c, a: v_apply_unit(c, a[0])),
    "apply-site": (1, lambda c, a: v_apply_site(c, a[0])),
    "swap-site": (1, lambda c, a: v_apply_site(c, a[0], swap_legacy=True)),
    "unswap-site": (1, lambda c, a: v_unswap_site(c, a[0])),
    "unit": (2, lambda c, a: v_unit(c, a[0], a[1])),
    "legacy-unit": (2, lambda c, a: v_legacy_unit(c, a[0], a[1])),
    "cert": (1, lambda c, a: v_cert(c, a[0])),
    "remove": (1, lambda c, a: v_remove(c, a[0])),
}


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if os.geteuid() != 0:
        print("ahost-helper must run as root (via sudo)", file=sys.stderr)
        return 2
    if not argv or argv[0] not in VERBS:
        print(f"usage: ahost-helper <{'|'.join(VERBS)}> ...", file=sys.stderr)
        return 2
    nargs, fn = VERBS[argv[0]]
    if len(argv) - 1 != nargs:
        print(f"{argv[0]} takes {nargs} argument(s)", file=sys.stderr)
        return 2
    os.umask(0o022)
    try:
        result = fn(_cfg(), argv[1:])
    except Exception as e:  # noqa: BLE001 - reported to caller, logged
        log(f"FAILED {' '.join(argv)}: {e}")
        print(json.dumps({"ok": False, "error": str(e)}))
        return 1
    print(json.dumps({"ok": True, **result}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
