"""ahost-helper: the only code that runs as root.

Invoked as `sudo /usr/local/sbin/ahost-helper <verb> [args]`. It takes app *names*, never file contents: it loads
the manifest itself, validates it (model + policy), and renders every file from its own templates. Config always
comes from /etc/ahost/ahost.toml (never from the environment or the caller).
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import syslog
from pathlib import Path

from . import host, policy, render
from .config import Config, load
from .manifest_io import load_all, load_app, load_router, load_routers, routers_dir
from .models import NAME_RE, App, Router
from .ports import Registry

CONFIG_PATH = Path("/etc/ahost/ahost.toml")
UNIT_ACTIONS = {"start", "stop", "restart", "enable", "disable", "reload"}


class HelperError(Exception):
    pass


def log(msg: str) -> None:
    caller = os.environ.get("SUDO_USER", "?")
    syslog.openlog("ahost-helper")
    syslog.syslog(syslog.LOG_INFO, f"caller={caller} {msg}")


def sh(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    r = subprocess.run(list(args), capture_output=True, text=True, check=False)
    if check and r.returncode != 0:
        raise HelperError(f"{' '.join(args)} failed ({r.returncode}): {r.stderr.strip() or r.stdout.strip()}")
    return r


# ---------------------------------------------------------------- loading & validation
def _cfg() -> Config:
    st = CONFIG_PATH.stat()
    if st.st_uid != 0 or st.st_mode & 0o022:
        raise HelperError(f"{CONFIG_PATH} must be owned by root and not group/world-writable")
    return load(CONFIG_PATH)


def _app(cfg: Config, name: str) -> App:
    if not NAME_RE.match(name):
        raise HelperError(f"invalid app name {name!r}")
    path = Path(cfg.paths.apps_dir) / f"{name}.toml"
    if path.is_symlink() or not path.is_file():
        raise HelperError(f"{path} is not a regular file")
    app = load_app(path)
    rep = policy.check(app, cfg)
    if not rep.ok:
        raise HelperError("policy: " + "; ".join(rep.errors))
    apps, _ = load_all(Path(cfg.paths.apps_dir))
    apps[name] = app
    dup = [e for e in policy.check_unique_domains(list(apps.values()), host.legacy_server_names(cfg))
           if any(f"domain {d} " in e for d in app.domains)]
    routers, _ = load_routers(Path(cfg.paths.apps_dir))
    taken = policy.reserved_domains(routers, cfg.ui.domain)
    dup += [f"domain {d} belongs to {taken[d]}" for d in app.domains if d in taken]
    if dup:
        raise HelperError("; ".join(dup))
    return app


def _registry(cfg: Config) -> Registry:
    Path(cfg.paths.state_dir).mkdir(parents=True, exist_ok=True, mode=0o750)
    return Registry(Path(cfg.paths.state_dir) / "ahost.db", cfg)


def _facts(cfg: Config, app: App) -> render.Facts:
    from .gpu import minor_map
    return render.Facts(certs_present=host.usable_certs(cfg, app.cert_groups()),
                        gpu_minors=minor_map() if any(p.gpus for p in app.processes.values()) else {},
                        manifest_path=str(Path(cfg.paths.apps_dir) / f"{app.name}.toml"))


# ---------------------------------------------------------------- file writing
def write_atomic(path: str, content: str, mode: int) -> bool:
    """Write if changed. Returns True when the file changed."""
    p = Path(path)
    if p.exists() and not p.is_symlink() and p.read_text() == content and (p.stat().st_mode & 0o777) == mode:
        return False
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_name(f".{p.name}.ahost-tmp")
    with open(tmp, "w") as f:
        f.write(content)
    os.chown(tmp, 0, 0)
    os.chmod(tmp, mode)
    os.replace(tmp, p)
    return True


def _allowed_path(cfg: Config, path: str) -> None:
    """Every write must land in one of AHost's own directories."""
    norm = os.path.normpath(path)
    prefixes = (f"{cfg.paths.etc_dir}/apps/", f"{cfg.paths.systemd_dir}/ahost@", f"{cfg.nginx.sites_dir}/")
    if norm != path or ".." in path.split("/") or not norm.startswith(prefixes):
        raise HelperError(f"refusing to write outside AHost directories: {path}")


# ---------------------------------------------------------------- verbs
def v_apply_unit(cfg: Config, name: str) -> dict:
    app = _app(cfg, name)
    reg = _registry(cfg)
    ports = reg.resolve(app, commit=True)
    facts = _facts(cfg, app)
    changed = []
    for pid in app.processes:
        for a in render.render_process(app, pid, ports.get(pid), cfg, facts):
            _allowed_path(cfg, a.path)
            if write_atomic(a.path, a.content, a.mode):
                changed.append(a.path)
    if app.multi:
        # the target groups the processes; each process is PartOf it
        tgt = f"{cfg.paths.systemd_dir}/ahost@{app.name}.target.d/override.conf"
        wants = "\n".join(f"Wants={app.unit(p)}" for p in app.processes)
        if write_atomic(tgt, f"# Generated by AHost.\n[Unit]\n{wants}\n", 0o644):
            changed.append(tgt)
    # remove files of processes that no longer exist
    live = {app.instance(p) for p in app.processes}
    for f in Path(cfg.paths.etc_dir, "apps").glob(f"{app.name}*"):
        inst = f.name.rsplit(".", 1)[0]
        if (inst == app.name or inst.startswith(app.name + ":")) and inst not in live:
            f.unlink()
            changed.append(str(f))
    if changed:
        sh("systemctl", "daemon-reload")
    log(f"apply-unit app={name} changed={len(changed)} ports={ports}")
    return {"changed": changed, "ports": ports}


def _nginx_test_or_restore(backups: dict[str, str | None], symlinks: dict[str, str | None]) -> None:
    r = sh("nginx", "-t", check=False)
    if r.returncode == 0:
        return
    for path, old in backups.items():
        if old is None:
            Path(path).unlink(missing_ok=True)
        else:
            Path(path).write_text(old)
    for link, target in symlinks.items():
        Path(link).unlink(missing_ok=True)
        if target is not None:
            os.symlink(target, link)
    raise HelperError(f"nginx -t failed, restored previous config:\n{r.stderr.strip()}")


def v_apply_site(cfg: Config, name: str, *, swap_legacy: bool = False) -> dict:
    app = _app(cfg, name)
    reg = _registry(cfg)
    ports = {a.process: a.port for a in reg.all() if a.app == name}
    missing = [p for p, proc in app.processes.items() if proc.port is not None and p not in ports]
    if missing:
        raise HelperError(f"ports not allocated for {missing}; run apply-unit first")
    site = render.render_site(app, ports, cfg, _facts(cfg, app))
    if site is None:
        return {"changed": []}
    _allowed_path(cfg, site.path)
    Path(cfg.nginx.log_dir).mkdir(parents=True, exist_ok=True)
    Path(cfg.certs.webroot).mkdir(parents=True, exist_ok=True)
    old = Path(site.path).read_text() if Path(site.path).exists() else None
    symlinks: dict[str, str | None] = {}
    legacy_names = host.legacy_server_names(cfg)
    still_legacy = sorted({legacy_names[d] for d in app.domains if d in legacy_names})
    if still_legacy and not swap_legacy:
        raise HelperError(f"legacy site(s) {still_legacy} still serve this app's domains; use swap-site")
    if swap_legacy:
        legacy = _legacy_site(cfg, app)
        link = Path(cfg.nginx.legacy_enabled) / legacy
        if link.is_symlink():
            symlinks[str(link)] = os.readlink(link)
            link.unlink()
        elif link.exists():
            raise HelperError(f"{link} is a regular file, not a symlink; move it to sites-available first")
    changed = write_atomic(site.path, site.content, site.mode)
    if changed or symlinks:
        _nginx_test_or_restore({site.path: old}, symlinks)
        sh("systemctl", "reload", "nginx")
    log(f"apply-site app={name} swap={swap_legacy} changed={changed}")
    return {"changed": [site.path] if changed else [], "legacy_disabled": list(symlinks)}


def _legacy_site(cfg: Config, app: App) -> str:
    allow = policy.read_list(Path(cfg.paths.etc_dir) / "legacy.allow")
    site = app.legacy.site if app.legacy else None
    if not site or f"site:{site}" not in allow:
        raise HelperError(f"legacy site {site!r} is not listed as 'site:{site}' in {cfg.paths.etc_dir}/legacy.allow")
    if "/" in site or site.startswith("."):
        raise HelperError("invalid legacy site name")
    return site


def _legacy_unit(cfg: Config, app: App) -> str:
    allow = policy.read_list(Path(cfg.paths.etc_dir) / "legacy.allow")
    unit = app.legacy.unit if app.legacy else None
    if not unit or f"unit:{unit}" not in allow:
        raise HelperError(f"legacy unit {unit!r} is not listed as 'unit:{unit}' in {cfg.paths.etc_dir}/legacy.allow")
    return unit


def v_unswap_site(cfg: Config, name: str) -> dict:
    """Rollback: remove the generated site and re-enable the legacy one, in one reload."""
    app = _app(cfg, name)
    legacy = _legacy_site(cfg, app)
    site_path = f"{cfg.nginx.sites_dir}/{name}.conf"
    old = Path(site_path).read_text() if Path(site_path).exists() else None
    link = Path(cfg.nginx.legacy_enabled) / legacy
    if not link.exists():
        os.symlink(f"../{Path(cfg.nginx.legacy_available).name}/{legacy}", link)
    Path(site_path).unlink(missing_ok=True)
    _nginx_test_or_restore({site_path: old}, {str(link): None})
    sh("systemctl", "reload", "nginx")
    log(f"unswap-site app={name}")
    return {"legacy_enabled": str(link)}


def v_unit(cfg: Config, action: str, name: str) -> dict:
    if action not in UNIT_ACTIONS:
        raise HelperError(f"unit action must be one of {sorted(UNIT_ACTIONS)}")
    app = _app(cfg, name)
    units = [app.unit(p) for p in app.processes]
    if app.multi:
        target = f"ahost@{app.name}.target"
        # start/stop/restart act on the target (processes are PartOf it); enable/disable on everything
        units = [target] if action in ("start", "stop", "restart") else [target, *units]
    sh("systemctl", action, *units)
    log(f"unit {action} app={name} units={units}")
    return {"units": units}


def v_legacy_unit(cfg: Config, action: str, name: str) -> dict:
    if action not in UNIT_ACTIONS:
        raise HelperError(f"unit action must be one of {sorted(UNIT_ACTIONS)}")
    unit = _legacy_unit(cfg, _app(cfg, name))
    sh("systemctl", action, unit)
    log(f"legacy-unit {action} app={name} unit={unit}")
    return {"unit": unit}


def v_cert(cfg: Config, name: str) -> dict:
    app = _app(cfg, name)
    missing = render.missing_certs(app, _facts(cfg, app))
    issued = []
    for cert, domains in app.cert_groups().items():
        if cert not in missing:
            continue
        args = ["certbot", "certonly", "--non-interactive", "--agree-tos", "--webroot", "-w", cfg.certs.webroot,
                "--cert-name", cert, "--deploy-hook", "systemctl reload nginx"]
        if cfg.certs.email:
            args += ["-m", cfg.certs.email]
        else:
            args += ["--register-unsafely-without-email"]
        for d in domains:
            args += ["-d", d]
        sh(*args)
        issued.append(cert)
    log(f"cert app={name} issued={issued}")
    return {"issued": issued}


def v_remove(cfg: Config, name: str) -> dict:
    if not NAME_RE.match(name):
        raise HelperError("invalid app name")
    removed = []
    units = [f.name.removesuffix(".service.d") for f in Path(cfg.paths.systemd_dir).glob(f"ahost@{name}*.service.d")
             if re.fullmatch(rf"ahost@{re.escape(name)}(:[a-z0-9-]+)?\.service\.d", f.name)]
    if units:
        sh("systemctl", "disable", "--now", *[f"{u}.service" for u in units], check=False)
    for u in units:
        d = Path(cfg.paths.systemd_dir) / f"{u}.service.d"
        shutil.rmtree(d)
        removed.append(str(d))
    for f in Path(cfg.paths.etc_dir, "apps").glob(f"{name}*"):
        inst = f.name.rsplit(".", 1)[0]
        if inst == name or inst.startswith(name + ":"):
            f.unlink()
            removed.append(str(f))
    site = Path(cfg.nginx.sites_dir) / f"{name}.conf"
    if site.exists():
        old = site.read_text()
        site.unlink()
        removed.append(str(site))
        _nginx_test_or_restore({str(site): old}, {})
        sh("systemctl", "reload", "nginx")
    sh("systemctl", "daemon-reload")
    _registry(cfg).release(name)
    log(f"remove app={name} removed={len(removed)}")
    return {"removed": removed}


def v_install(cfg: Config) -> dict:
    """Install the shared files (template units, nginx common/default). Idempotent."""
    changed = []
    Path(cfg.nginx.sites_dir).mkdir(parents=True, exist_ok=True)
    Path(cfg.paths.etc_dir, "apps").mkdir(parents=True, exist_ok=True, mode=0o755)
    Path(cfg.nginx.log_dir).mkdir(parents=True, exist_ok=True)
    Path(cfg.certs.webroot).mkdir(parents=True, exist_ok=True)
    backups = {}
    for a in render.render_static(cfg):
        if a.path.startswith(cfg.nginx.sites_dir):
            backups[a.path] = Path(a.path).read_text() if Path(a.path).exists() else None
        if write_atomic(a.path, a.content, a.mode):
            changed.append(a.path)
    if any(p.startswith(cfg.nginx.sites_dir) for p in changed):
        _nginx_test_or_restore({p: backups[p] for p in changed if p in backups}, {})
        sh("systemctl", "reload", "nginx")
    if any(p.startswith(cfg.paths.systemd_dir) for p in changed):
        sh("systemctl", "daemon-reload")
    log(f"install changed={changed}")
    return {"changed": changed}


# ---------------------------------------------------------------- routers
def _router(cfg: Config, name: str) -> Router:
    if not NAME_RE.match(name):
        raise HelperError(f"invalid router name {name!r}")
    d = routers_dir(Path(cfg.paths.apps_dir))
    path = d / f"{name}.toml"
    if d.is_symlink() or path.is_symlink() or not path.is_file():
        raise HelperError(f"{path} is not a regular file")
    return load_router(path)


def _router_apps(cfg: Config, router: Router) -> dict[str, App]:
    """The router's apps, each validated like `_app` does (their routes end up in root's nginx config)."""
    out = {}
    for e in router.entries:
        if e.app and e.app not in out and (Path(cfg.paths.apps_dir) / f"{e.app}.toml").is_file():
            out[e.app] = _app(cfg, e.app)
    return out


def v_apply_router(cfg: Config, name: str) -> dict:
    """Write the router's nginx site; get its certificate the first time (then write it again with HTTPS)."""
    router = _router(cfg, name)
    apps = _router_apps(cfg, router)
    all_apps, _ = load_all(Path(cfg.paths.apps_dir))
    routers, _ = load_routers(Path(cfg.paths.apps_dir))
    errs = policy.check_router(router, list(all_apps.values()), routers, host.legacy_server_names(cfg), cfg.ui.domain)
    if errs:
        raise HelperError("; ".join(errs))
    ports: dict[str, dict[str, int]] = {}
    for a in _registry(cfg).all():
        ports.setdefault(a.app, {})[a.process] = a.port
    facts = render.Facts(certs_present=host.usable_certs(cfg, {router.cert_name: [router.domain]}),
                         manifest_path=str(routers_dir(Path(cfg.paths.apps_dir)) / f"{name}.toml"))
    Path(cfg.nginx.log_dir).mkdir(parents=True, exist_ok=True)
    Path(cfg.certs.webroot).mkdir(parents=True, exist_ok=True)
    changed, issued, warnings = False, False, []
    for _ in range(2):
        try:
            site, warnings = render.render_router(router, apps, ports, cfg, facts)
        except ValueError as e:
            raise HelperError(str(e)) from e
        _allowed_path(cfg, site.path)
        old = Path(site.path).read_text() if Path(site.path).exists() else None
        if write_atomic(site.path, site.content, 0o644):
            changed = True
            _nginx_test_or_restore({site.path: old}, {})
            sh("systemctl", "reload", "nginx")
        if router.cert_name in facts.certs_present:
            break
        args = ["certbot", "certonly", "--non-interactive", "--agree-tos", "--webroot", "-w", cfg.certs.webroot,
                "--cert-name", router.cert_name, "-d", router.domain, "--deploy-hook", "systemctl reload nginx"]
        args += ["-m", cfg.certs.email] if cfg.certs.email else ["--register-unsafely-without-email"]
        sh(*args)
        issued = True
        facts.certs_present.add(router.cert_name)
    log(f"apply-router router={name} changed={changed} issued={issued}")
    return {"changed": changed, "cert_issued": issued, "warnings": warnings}


def v_remove_router(cfg: Config, name: str) -> dict:
    """Take the router's site down. Its file under routers/ and its certificate are kept."""
    if not NAME_RE.match(name):
        raise HelperError("invalid router name")
    site = Path(render.router_site_path(cfg, name))
    if not site.exists():
        return {"removed": []}
    old = site.read_text()
    site.unlink()
    _nginx_test_or_restore({str(site): old}, {})
    sh("systemctl", "reload", "nginx")
    log(f"remove-router router={name}")
    return {"removed": [str(site)]}


# ---------------------------------------------------------------- ddclient
def _ddclient_desired(cfg: Config) -> set[str]:
    apps, _ = load_all(Path(cfg.paths.apps_dir))
    routers, _ = load_routers(Path(cfg.paths.apps_dir))
    hosts = {d for a in apps.values() for d in a.domains} | set(cfg.dns.static_hosts)
    hosts |= {r.domain for r in routers.values()}
    if cfg.ui.domain:
        hosts.add(cfg.ui.domain)
    return hosts


def v_ddclient(cfg: Config, mode: str) -> dict:
    """plan: show host changes. apply: rewrite host lines (credentials untouched), restart ddclient."""
    from . import ddclient
    if cfg.dns.provider != "ddclient":
        raise HelperError("dns.provider is not 'ddclient'")
    conf = Path(cfg.dns.ddclient_conf)
    text = conf.read_text()
    plan = ddclient.sync(text, _ddclient_desired(cfg))
    result = {"added": plan.added, "removed": plan.removed, "unplaceable": plan.unplaceable,
              "changed": plan.changed}
    if mode == "plan" or not plan.changed:
        return result
    if mode != "apply":
        raise HelperError("usage: ddclient <plan|apply>")
    st = conf.stat()
    backup = conf.with_name(f"{conf.name}.ahost-bak")
    backup.write_text(text)
    os.chmod(backup, 0o600)
    tmp = conf.with_name(f".{conf.name}.ahost-tmp")
    tmp.write_text(plan.new_text)
    os.chown(tmp, st.st_uid, st.st_gid)
    os.chmod(tmp, st.st_mode & 0o777)
    os.replace(tmp, conf)
    r = sh("systemctl", "restart", "ddclient", check=False)
    if r.returncode != 0:
        os.replace(backup, conf)
        sh("systemctl", "restart", "ddclient", check=False)
        raise HelperError(f"ddclient failed to restart with the new host list; restored: {r.stderr.strip()}")
    log(f"ddclient apply added={plan.added} removed={plan.removed}")
    result["backup"] = str(backup)
    return result


# ---------------------------------------------------------------- UI site
def _ui_app(cfg: Config) -> App:
    host, _, port = cfg.ui.bind.rpartition(":")
    if host not in ("127.0.0.1", "localhost") or not port.isdigit():
        raise HelperError("ui.bind must be 127.0.0.1:<port>")
    if not cfg.ui.domain:
        raise HelperError("ui.domain is not set in the config")
    return App.model_validate({
        "name": "ahost-ui", "workdir": "/opt/ahost", "domains": [cfg.ui.domain],
        "processes": {"main": {"command": "ahost serve", "port": int(port)}},
        "routes": [{"path": "/", "to": "main", "streaming": True, "websocket": True, "timeout": "1h"}],
        "proxy": {"max_body": "5m"},
    })


def v_ui_site(cfg: Config) -> dict:
    """nginx site (+ certificate) for the dashboard. The dashboard itself is ahost.service, not an ahost@ app."""
    app = _ui_app(cfg)
    port = app.processes["main"].port
    legacy = host.legacy_server_names(cfg)
    if cfg.ui.domain in legacy:
        raise HelperError(f"{cfg.ui.domain} is already served by legacy site {legacy[cfg.ui.domain]}")
    Path(cfg.nginx.log_dir).mkdir(parents=True, exist_ok=True)
    Path(cfg.certs.webroot).mkdir(parents=True, exist_ok=True)
    facts = render.Facts(certs_present=host.usable_certs(cfg, {"ahost-ui": [cfg.ui.domain]}),
                         manifest_path="/etc/ahost/ahost.toml [ui]")
    path = f"{cfg.nginx.sites_dir}/ahost-ui.conf"
    issued = False
    # Until the certificate exists, port 80 only answers ACME challenges and returns 503: never serve the login
    # page over plain HTTP.
    pre_cert = app.model_copy(update={"routes": [app.routes[0].model_copy(update={"to": None, "status": 503,
                                                                                    "websocket": False,
                                                                                    "streaming": False,
                                                                                    "timeout": None})]})
    for _ in range(2):
        site = render.render_site(app if "ahost-ui" in facts.certs_present else pre_cert, {"main": port}, cfg, facts)
        old = Path(path).read_text() if Path(path).exists() else None
        if write_atomic(path, site.content, 0o644):
            _nginx_test_or_restore({path: old}, {})
            sh("systemctl", "reload", "nginx")
        if "ahost-ui" in facts.certs_present:
            break
        args = ["certbot", "certonly", "--non-interactive", "--agree-tos", "--webroot", "-w", cfg.certs.webroot,
                "--cert-name", "ahost-ui", "-d", cfg.ui.domain, "--deploy-hook", "systemctl reload nginx"]
        args += ["-m", cfg.certs.email] if cfg.certs.email else ["--register-unsafely-without-email"]
        sh(*args)
        issued = True
        facts.certs_present.add("ahost-ui")
    log(f"ui-site domain={cfg.ui.domain} issued={issued}")
    return {"domain": cfg.ui.domain, "cert_issued": issued}


# ---------------------------------------------------------------- nginx logs (read-only)
def v_nginx_log(cfg: Config, name: str, kind: str, lines: str) -> dict:
    router = name.removeprefix("router.")
    if not NAME_RE.match(name) and name != "ahost-ui" and not (name.startswith("router.") and NAME_RE.match(router)):
        raise HelperError("invalid app name")
    if kind not in ("access", "error"):
        raise HelperError("kind must be access or error")
    if not lines.isdigit() or not (1 <= int(lines) <= 5000):
        raise HelperError("lines must be 1..5000")
    path = Path(cfg.nginx.log_dir) / f"{name}.{kind}.log"
    if not path.exists():
        return {"lines": []}
    r = sh("tail", "-n", lines, str(path))
    return {"lines": r.stdout.splitlines()}


VERBS = {
    "install": (0, lambda c, a: v_install(c)),
    "apply-unit": (1, lambda c, a: v_apply_unit(c, a[0])),
    "apply-site": (1, lambda c, a: v_apply_site(c, a[0])),
    "swap-site": (1, lambda c, a: v_apply_site(c, a[0], swap_legacy=True)),
    "unswap-site": (1, lambda c, a: v_unswap_site(c, a[0])),
    "unit": (2, lambda c, a: v_unit(c, a[0], a[1])),
    "legacy-unit": (2, lambda c, a: v_legacy_unit(c, a[0], a[1])),
    "cert": (1, lambda c, a: v_cert(c, a[0])),
    "remove": (1, lambda c, a: v_remove(c, a[0])),
    "apply-router": (1, lambda c, a: v_apply_router(c, a[0])),
    "remove-router": (1, lambda c, a: v_remove_router(c, a[0])),
    "ddclient": (1, lambda c, a: v_ddclient(c, a[0])),
    "ui-site": (0, lambda c, a: v_ui_site(c)),
    "nginx-log": (3, lambda c, a: v_nginx_log(c, a[0], a[1], a[2])),
}


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if os.geteuid() != 0:
        print("ahost-helper must run as root (via sudo)", file=sys.stderr)
        return 2
    if not argv or argv[0] not in VERBS:
        print(f"usage: ahost-helper <{'|'.join(VERBS)}> ...", file=sys.stderr)
        return 2
    nargs, fn = VERBS[argv[0]]
    if len(argv) - 1 != nargs:
        print(f"{argv[0]} takes {nargs} argument(s)", file=sys.stderr)
        return 2
    os.umask(0o022)
    try:
        result = fn(_cfg(), argv[1:])
    except Exception as e:  # noqa: BLE001 - reported to caller, logged
        log(f"FAILED {' '.join(argv)}: {e}")
        print(json.dumps({"ok": False, "error": str(e)}))
        return 1
    print(json.dumps({"ok": True, **result}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
